package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/ahacop/pgbox/internal/config"
	"github.com/ahacop/pgbox/pkg/extensions"
)

type Scaffold struct {
	Path   string
	Config *config.Config
	ExtMgr *extensions.Manager
}

func NewScaffold(cfg *config.Config, extMgr *extensions.Manager, targetDir string) (*Scaffold, error) {
	var scaffoldPath string

	if targetDir != "" {
		scaffoldPath = targetDir
		if err := os.MkdirAll(scaffoldPath, 0755); err != nil {
			return nil, fmt.Errorf("failed to create target directory: %w", err)
		}
	} else {
		// Create temporary directory
		tempDir, err := os.MkdirTemp(cfg.RunDirBase, cfg.Name+".*.scaffold")
		if err != nil {
			return nil, fmt.Errorf("failed to create temp directory: %w", err)
		}
		scaffoldPath = tempDir
	}

	// Create initdb directory
	if err := os.MkdirAll(filepath.Join(scaffoldPath, "initdb"), 0755); err != nil {
		return nil, fmt.Errorf("failed to create initdb directory: %w", err)
	}

	return &Scaffold{
		Path:   scaffoldPath,
		Config: cfg,
		ExtMgr: extMgr,
	}, nil
}

func (s *Scaffold) Generate(extensionList []string) error {
	if err := s.generateDockerfile(extensionList); err != nil {
		return fmt.Errorf("failed to generate Dockerfile: %w", err)
	}

	if err := s.generateDockerCompose(); err != nil {
		return fmt.Errorf("failed to generate docker-compose.yml: %w", err)
	}

	if err := s.generateInitSQL(extensionList); err != nil {
		return fmt.Errorf("failed to generate init SQL: %w", err)
	}

	return nil
}

func (s *Scaffold) generateDockerfile(extensionList []string) error {
	var dockerfile strings.Builder

	dockerfile.WriteString(fmt.Sprintf("ARG PG_MAJOR=%s\n", s.Config.PgMajor))
	dockerfile.WriteString("FROM postgres:${PG_MAJOR}\n\n")

	// Check if we need apt packages
	needAptPackages := false
	var aptPackages []string

	for _, extName := range extensionList {
		if !s.ExtMgr.IsBuiltinExtension(extName) {
			needAptPackages = true
			if pkg := s.ExtMgr.GetExtensionPackage(extName); pkg != "" {
				aptPackages = append(aptPackages, pkg)
			}
		}
	}

	if needAptPackages {
		dockerfile.WriteString("RUN set -eux; \\\n")
		dockerfile.WriteString("    apt-get update; \\\n")
		dockerfile.WriteString("    apt-get install -y --no-install-recommends curl gnupg ca-certificates; \\\n")
		dockerfile.WriteString("    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql.gpg; \\\n")
		dockerfile.WriteString("    echo \"deb [signed-by=/usr/share/keyrings/postgresql.gpg] https://apt.postgresql.org/pub/repos/apt bookworm-pgdg main\" > /etc/apt/sources.list.d/pgdg.list; \\\n")
		dockerfile.WriteString("    apt-get update; \\\n")
		dockerfile.WriteString("    apt-get install -y --no-install-recommends \\\n")

		for _, pkg := range aptPackages {
			dockerfile.WriteString(fmt.Sprintf("        %s \\\n", pkg))
		}

		dockerfile.WriteString("    ; \\\n")
		dockerfile.WriteString("    apt-get purge -y --auto-remove curl gnupg; rm -rf /var/lib/apt/lists/*\n")
	}

	return os.WriteFile(filepath.Join(s.Path, "Dockerfile"), []byte(dockerfile.String()), 0644)
}

func (s *Scaffold) generateDockerCompose() error {
	compose := fmt.Sprintf(`services:
  db:
    build:
      context: .
      args: { PG_MAJOR: "%s" }
    container_name: %s
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: changeme
    ports: ["%s:5432"]
    volumes:
      - %s:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 3s
      timeout: 2s
      retries: 20
volumes:
  %s:
`, s.Config.PgMajor, s.Config.Name, s.Config.Port, s.Config.DataVol, s.Config.DataVol)

	return os.WriteFile(filepath.Join(s.Path, "docker-compose.yml"), []byte(compose), 0644)
}

func (s *Scaffold) generateInitSQL(extensionList []string) error {
	var sql strings.Builder

	sql.WriteString("-- generated by pgbox\n")
	sql.WriteString(fmt.Sprintf("-- Generated at: %s\n", time.Now().Format(time.RFC3339)))
	sql.WriteString("-- Extensions loaded from pgbox-data JSON files\n\n")

	for _, extName := range extensionList {
		ext, found := s.ExtMgr.GetExtensionInfo(extName)
		if found {
			sql.WriteString(fmt.Sprintf("-- %s: %s (%s)\n", ext.Name, ext.Description, ext.Kind))
		} else {
			sql.WriteString(fmt.Sprintf("-- %s: (unknown extension)\n", extName))
		}
		sql.WriteString(fmt.Sprintf("CREATE EXTENSION IF NOT EXISTS %s;\n\n", extName))
	}

	return os.WriteFile(filepath.Join(s.Path, "initdb", "01-extensions.sql"), []byte(sql.String()), 0644)
}
