# wal2json - PostgreSQL logical decoding JSON output plugin
# Enhanced configuration for logical replication

extension = "wal2json"
display_name = "wal2json"
package = "postgresql-17-wal2json"
description = "PostgreSQL logical decoding JSON output plugin"

[image]
apt_packages = ["postgresql-17-wal2json"]

[postgresql.conf]
shared_preload_libraries = ["wal2json"]
"wal_level" = "logical"
"max_replication_slots" = "10"
"max_wal_senders" = "10"

# wal2json is an output plugin, not a regular extension
# No CREATE EXTENSION needed, but we can add a comment
[[sql.initdb]]
text = """
-- wal2json logical decoding plugin is now available
-- To use it, create a replication slot with:
-- SELECT pg_create_logical_replication_slot('slot_name', 'wal2json');
"""

[pgbox]
needs_restart = true
