# pg_cron - Run periodic jobs in PostgreSQL
# Enhanced configuration with shared_preload_libraries

extension = "pg_cron"
display_name = "pg_cron"
package = "postgresql-17-cron"
description = "Run periodic jobs in PostgreSQL"
min_pg = "14"

[image]
apt_packages = ["postgresql-17-cron"]

[postgresql.conf]
shared_preload_libraries = ["pg_cron"]
"cron.database_name" = "postgres"
"cron.max_running_jobs" = "5"

# SQL initialization
[[sql.initdb]]
text = """
CREATE EXTENSION IF NOT EXISTS pg_cron;
GRANT USAGE ON SCHEMA cron TO postgres;
"""

[pgbox]
needs_restart = true
